version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html

hooks:
   AfterInstall:
    - location: /scripts/install.sh
      runas: root
      timeout: 500
      
   ApplicationStop:
    - location: /scripts/stop.sh
      runas: root
      timeout: 300
      
    ApplicationStart:
      - location: /scripts/start.sh
        timeout: 300
        runas: root
