version: 0.2

run as: root

env:
  parameter store:
            DB_NAME: ""
            DB_HOST: ""
            DB_USER: ""
            DB_PASSWORD: ""
  
phases:
  pre_build:
    commands:
        echo "Importing DB Credentials"
            - sed -i 's/database_name/'$DB_NAME'/' wp-config.php
            - sed -i 's/username/'$DB_USER'/' wp-config.php
            - sed -i 's/password/'$DB_PASSWORD'/' wp-config.php
            - sed -i 's/localhost/'$DB_HOST'/' wp-config.php
            
artifacts:
  files: 
      echo "Creating Artifacts"
      - '**/*'

