version: 0.2

run-as: root

env:
  parameter-store:
            DB_NAME: "/divye/dbName"
            DB_HOST: "/divye/dbEndpoint"
            DB_USER: "/divye/DbUser"
            DB_PASSWORD: "/divye/DbPassword"
  
phases:
  pre_build:
    commands:
            - apt update -y
            - echo "Installing Wordpress dependencies"
            - apt install nginx -y
            - apt install php php-fpm -y
            
  build:
    commands:
            - sed -i 's/database_name_here/'$DB_NAME'/' wp-config.php
            - sed -i 's/username_here/'$DB_USER'/' wp-config.php
            - sed -i 's/password_here/'$DB_PASSWORD'/' wp-config.php
            - sed -i 's/localhost/'$DB_HOST'/' wp-config.php
            - printenv
            
artifacts:
  files: 
      - '**/*'

